- code/create-system-account/create-system-account.en.ts
- code/rent-exemption/rent-exemption.en.sh
- code/rent-exemption/rent-exemption.en.ts
- docs/.vuepress/config.ts
- docs/recipes/accounts.md
- build(vuepress): add new page under recipes
- feat(create system account): add ts code snippet for creating a system account
- docs(accounts): recipe for creating a system account
> add accounts recipe

- code/staking/create-stake-account/create-stake-account.en.ts
- code/staking/deactivate-stake/deactivate-stake.en.ts
- code/staking/delegate-stake/delegate-stake.en.ts
- code/staking/get-current-validators/get-current-validators.en.sh
- code/staking/get-current-validators/get-current-validators.en.ts
- code/staking/withdraw-stake/withdraw-stake.en.ts
- docs/.vuepress/config.ts
- docs/recipes/staking.md
- yarn.lock
Trying again for Vercel bot fix
This addresses #6 
- Get Current Validators
- Create Stake Account
- Delegate Stake
- Deactivate Stake
- Withdraw Stake
> feat(staking): add staking section

- code/basic-transactions/memo/memo.adapter.en.tsx
- code/basic-transactions/memo/memo.en.sh
- code/basic-transactions/memo/memo.en.ts
- docs/recipes/basic-transactions.md
Closes #28 
Memo in basic-transactions.
> feat(memo): Add Memo Transaction Snippet

- code/keypairs-and-wallets/generate-keypair/generate-keypair.preview.en.sh
- code/keypairs-and-wallets/generate-keypair/generate-keypair.preview.en.ts
- docs/.vuepress/clientAppEnhance.js
- docs/.vuepress/components/SolanaCodeGroup.vue
- docs/.vuepress/components/SolanaCodeGroupItem.vue
- docs/.vuepress/config.ts
- docs/.vuepress/styles/index.scss
- docs/recipes/keypairs-and-wallets.md
- package.json
> feat: add code previews

- code/offline-transactions/sign-transaction/main.en.ts
> Offline Transaction

- code/offline-transactions/sign-transaction/main.en.ts
add a extra step, verify signature, before composing transaction
> feat(offline-transaciton): add verify signature

- code/staking/create-stake-account/create-stake-account.preview.en.ts
- code/staking/deactivate-stake/deactivate-stake.preview.en.ts
- code/staking/delegate-stake/delegate-stake.preview.en.ts
- code/staking/withdraw-stake/withdraw-stake.preview.en.ts
- docs/recipes/staking.md
- yarn.lock
> feat(preview): Add previews to Staking

- code/accounts/create-system-account/create-system-account.preview.en.ts
- code/accounts/program-derived-address/sign-a-pda/client/main.preview.en.ts
- code/accounts/program-derived-address/sign-a-pda/program/src/lib.preview.rs
- docs/recipes/accounts.md
Closes #54 
Preview added to accounts section
> feat(preview): Add previews to Accounts

- docs/.vuepress/styles/index.scss
> style: change bg of code element in tip container

- code/offline-transactions/durable-nonce/create-nonce-account/main.preview.en.ts
- code/offline-transactions/durable-nonce/get-nonce-account/main.preview.en.ts
- code/offline-transactions/durable-nonce/use-nonce-account/main.preview.en.ts
- code/offline-transactions/sign-transaction/main.preview.en.ts
- docs/recipes/offline-transactions.md
> feat(preview): Add previews to offline transaction

- code/token/approve/main.en.ts
- code/token/approve/main.preview.en.ts
- code/token/burn-token/burn-token.en.ts
- code/token/burn-token/burn-token.preview.en.ts
- code/token/close-token-account/close-token-account.en.ts
- code/token/close-token-account/close-token-account.preview.en.ts
- code/token/create-mint-account/create-mint-account.preview.en.ts
- code/token/create-token-account/ata.preview.en.ts
- code/token/create-token-account/random.preview.en.ts
- code/token/get-mint-account/get-mint-account.preview.en.ts
- code/token/get-token-account-by-owner/all.preview.en.ts
- code/token/get-token-account-by-owner/by-mint.preview.en.ts
- code/token/get-token-account/get-token-account.preview.en.ts
- code/token/get-token-balance/get-token-balance.preview.en.ts
- code/token/mint-token/mint-token.en.ts
- code/token/mint-token/mint-token.preview.en.ts
- code/token/revoke/main.en.ts
- code/token/revoke/main.preview.en.ts
- code/token/set-authority/main.preview.en.ts
- code/token/transfer-token/transfer-token.preview.en.ts
- code/token/wrapped-sol/add-balance-by-sol.preview.en.ts
- code/token/wrapped-sol/add-balance-by-token.en.ts
- code/token/wrapped-sol/add-balance-by-token.preview.en.ts
- docs/recipes/token.md
> token code preview

- docs/.vuepress/config.ts
- docs/core-concepts/programs.md
> feat(programs): create programs core concept

- docs/.vuepress/config.ts
- docs/core-concepts/programs.md
- docs/core-concepts/transactions.md
Adds a core concept for Transactions
> feat(transactions): add transaction core concept

- code/nfts/get-owner/get-owner.en.ts
- code/nfts/get-owner/get-owner.preview.en.ts
- docs/recipes/nfts.md
This targets parts of https://github.com/solana-dev-adv/solana-cookbook/issues/23
> Add recipe for getting the owner of an NFT

- code/name-service/find-for-owner/find-for-owner.en.ts
- code/name-service/find-for-owner/find-for-owner.preview.en.ts
- code/name-service/resolve-sol-domain/resolve-sol-domain.en.ts
- code/name-service/resolve-sub-domain/resolve-sub-domain.en.ts
- code/name-service/resolve-sub-domain/resolve-sub-domain.preview.en.ts
- code/name-service/resolve-twitter/resolve-twitter.en.ts
- code/name-service/resolve-twitter/resolve-twitter.preview.en.ts
- code/name-service/reverse-look-up-domain/reverse-look-up-domain.en.ts
- code/name-service/reverse-look-up-domain/reverse-look-up-domain.preview.en.ts
- code/name-service/reverse-look-up-twitter/reverse-look-up-twitter.en.ts
- code/name-service/reverse-look-up-twitter/reverse-look-up-twitter.preview.en.ts
- code/name-service/schema/schema.en.ts
- code/name-service/schema/schema.preview.en.ts
- docs/recipes/name-service.md
Add the following section:
- Name registry
- Resolve subdomain
- Perform reverse look up of domains
- Retrieve all domains of a wallet
- Resolve a Twitter handle
- Reverse look up of Twitter handle
> add name service sections

- docs/.vuepress/components/SolanaCodeGroup.vue
- Added a copy button to the custom code group component
- Changed buttons to SVG icons from [Heroicons](https://heroicons.com/)
> add copy button to code group

- code/keypairs-and-wallets/generate-mnemonic/from-bip39.preview.ts
- code/keypairs-and-wallets/generate-mnemonic/from-bip39.sh
- code/keypairs-and-wallets/generate-mnemonic/from-bip39.ts
- docs/recipes/keypairs-and-wallets.md
- Added a section for generation of mnemonic phrase through TS and CLI
> added mnemonic phrase generation section

- docs/core-concepts/accounts.md
- docs/core-concepts/programs.md
- docs/core-concepts/transactions.md
- docs/getting-started/installation.md
- docs/ingredients/get-program-accounts.md
- docs/ingredients/serialization.md
- docs/recipes/accounts.md
- docs/recipes/basic-transactions.md
- docs/recipes/keypairs-and-wallets.md
- docs/recipes/local-development.md
- docs/recipes/name-service.md
- docs/recipes/nfts.md
- docs/recipes/offline-transactions.md
- docs/recipes/programs.md
- docs/recipes/staking.md
- docs/recipes/token.md
> feat(SEO): Updated Meta Descriptions

- code/local-development/airdropping-sol/airdropping-sol.en.rs
- code/local-development/airdropping-sol/airdropping-sol.preview.en.rs
- code/local-development/connecting-cluster/connecting-cluster.en.rs
- code/local-development/connecting-cluster/connecting-cluster.preview.en.rs
- code/local-development/connecting-private-cluster/connecting-private-cluster.en.rs
- code/local-development/connecting-private-cluster/connecting-private-cluster.preview.en.rs
- docs/recipes/local-development.md
This pull request addresses the following snippets in the recipe.
1. Connect to a cluster
2. Connect to a private cluster
3. Request Airdrop
> Rust implementation for local development. Towards #127

- code/basic-transactions/sending-sol/sending-sol.en.py
- code/basic-transactions/sending-sol/sending-sol.preview.en.py
- docs/recipes/basic-transactions.md
Code for sending SOL transactions in Python using the library Solana.py (https://github.com/michaelhly/solana-py)
> 📝 Added python code for sending transaction

- code/local-development/connecting-websocket/connecting-websocket.en.rs
- code/local-development/connecting-websocket/connecting-websocket.preview.en.rs
- docs/recipes/local-development.md
> feat(rust) Add websocket connection

- code/basic-transactions/sending-sol/sending-sol.en.rs
- code/basic-transactions/sending-sol/sending-sol.preview.rs
- docs/recipes/basic-transactions.md
As per discussion here: https://github.com/solana-dev-adv/solana-cookbook/issues/127
Rewriting basic transactions in rust.
> Adding Rust implementation for basic transaction sending sol

- docs/core-concepts/programs.md
fixed incorrect spelling of Instruction
> Fixed spelling mistake

- code/nfts/nfts-mint-addresses/mint-addresses-preview.en.ts
- code/nfts/nfts-mint-addresses/mint-addresses.en.ts
- docs/recipes/nfts.md
adding the code to find the NFT mint addresses generated given Candy Machine public address.
> feat(NFT) add mint addresses

- code/staking/get-delegators-by-validators/get-delegators-by-validators.en.ts
- code/staking/get-delegators-by-validators/get-delegators-by-validators.preview.en.ts
- docs/recipes/staking.md
Added snippet to fetch delegators as suggested in issue: #45
> feat: added snippet to fetch delegators of validators

- code/accounts/rent-exemption/rent-exemption.en.rs
- docs/recipes/accounts.md
rust snippet for rent exemption
re #127
> docs(account): rust snippet for rent exemption

- code/accounts/create-account-with-seed/generate/main.en.rs
- code/accounts/create-account-with-seed/generate/main.preview.en.rs
- docs/recipes/accounts.md
rust snippet: derive pubkey with seed
re #127
> docs(account): rust snippet

- code/accounts/create-account-with-seed/creation/main.en.rs
- code/accounts/create-account-with-seed/creation/main.preview.en.rs
- docs/recipes/accounts.md
rust snippet for creating an account with seed
re #127
> docs(accounts): create account with seed

- code/accounts/program-derived-address/derived-a-pda/create-program-address.en.rs
- code/accounts/program-derived-address/derived-a-pda/find-program-address.en.rs
- docs/recipes/accounts.md
rust snippets for generating a pda
re #127
> docs(recipe/accounts): generate pda

- code/get-program-accounts/basic/basic.en.rs
- docs/recipes/accounts.md
rust snippets for get program accounts
re #127
> docs(recipes/accounts): get program accounts

- code/accounts/get-balance/main.en.rs
- code/accounts/get-balance/main.preview.en.rs
- docs/recipes/accounts.md
rust snippets for getting an accounts balance
re #127
> docs(recipes/accounts): get balance

- code/nfts/upload-arweave/upload-arweave.en.py
- code/nfts/upload-arweave/upload-arweave.preview.en.py
- docs/recipes/nfts.md
> adding python snippet for uploading metadata to arweave

- code/token/get-token-balance/get-token-balance.en.rs
- code/token/get-token-balance/get-token-balance.preview.en.rs
- docs/recipes/token.md
This is the Rust Implementation for Get Token Balance
> Get Token Balance

- docs/recipes/anchor.md
PR for Issue #87 
@jacobcreech I've added a list of anchor error codes after going through the code, hope this up to the mark
> Added a list of anchor error codes

- code/basic-transactions/sending-sol/sending-sol.en.rs
Added the creation and sending of the transaction using the transfer instruction
closes #174
> fix: update send sol rust impl

- code/nfts/nfts-mint-addresses/mint-addresses-preview-v2.en.ts
- code/nfts/nfts-mint-addresses/mint-addresses-preview.en.ts
- code/nfts/nfts-mint-addresses/mint-addresses-v2.en.ts
- code/nfts/nfts-mint-addresses/mint-addresses.en.ts
- docs/references/nfts.md
See #180
I added code snippets for Candy Machines v2 and updated the code for Candy Machines v1 to make it simpler, more performant and more consistent with v2.
> Update "Get NFT Mint Addresses" section

- code/local-development/airdropping-sol/airdropping-sol.en.py
- code/local-development/airdropping-sol/airdropping-sol.preview.en.py
- code/local-development/connecting-cluster/connecting-cluster.en.py
- code/local-development/connecting-cluster/connecting-cluster.preview.en.py
- code/local-development/connecting-private-cluster/connecting-private-cluster.en.py
- code/local-development/connecting-private-cluster/connecting-private-cluster.preview.en.py
- code/local-development/connecting-websocket/connecting-websocket.en.py
- code/local-development/connecting-websocket/connecting-websocket.preview.en.py
- docs/references/local-development.md
Towards #133 
- Adding python implementation for Local Development Document.
- Includes snippets for Setting Up Connections, Subscribing to WebSocket, and Airdropping SOL.
> feat(python): Add python impl for local development

- code/local-development/using-mainnet-accounts/dump-accounts.en.sh
- code/local-development/using-mainnet-accounts/dump-accounts.preview.en.sh
- code/local-development/using-mainnet-accounts/dump-programs.en.sh
- code/local-development/using-mainnet-accounts/dump-programs.preview.en.sh
- code/local-development/using-mainnet-accounts/load-accounts.en.sh
- code/local-development/using-mainnet-accounts/load-accounts.preview.en.sh
- code/local-development/using-mainnet-accounts/load-all.en.sh
- code/local-development/using-mainnet-accounts/load-all.preview.en.sh
- code/local-development/using-mainnet-accounts/load-programs.en.sh
- code/local-development/using-mainnet-accounts/load-programs.preview.en.sh
- docs/references/local-development.md
> Add reference for using mainnet accounts on localnet

- docs/guides/retrying-transactions.md
Small but important typo here! Was caught by someone on Twitter
> fix(retry-transactions): keep skipPreflight as false

- .gitignore
- CONTRIBUTING.md
- docs/README.md
- docs/core-concepts/accounts.md
- docs/core-concepts/programs.md
- docs/getting-started/installation.md
- docs/references/local-development.md
- docs/references/name-service.md
> added link to web3.js lib + assorted cleanup

- docs/guides/debugging-solana-programs.md
- docs/guides/feature-parity-testing.md
- docs/guides/serialization.md
In closing #235 I had typos
This fixes those as well as a few others
> Fix various typos and complete #235

- code/accounts/get-balance/main.en.py
- code/accounts/get-balance/main.preview.en.py
- docs/references/accounts.md
Adding a code a snippet for getting a balance using python - references issue #133 
will work on adding more snippets
> Add code snippet for python get balance

- code/token/approve/main.en.ts
- code/token/approve/main.preview.en.ts
- code/token/burn-token/burn-token.en.ts
- code/token/burn-token/burn-token.preview.en.ts
- code/token/close-token-account/close-token-account.en.ts
- code/token/close-token-account/close-token-account.preview.en.ts
- code/token/create-mint-account/create-mint-account.en.ts
- code/token/create-mint-account/create-mint-account.preview.en.ts
- code/token/create-token-account/ata.en.ts
- code/token/create-token-account/ata.preview.en.ts
- code/token/create-token-account/random.en.ts
- code/token/create-token-account/random.preview.en.ts
- code/token/get-mint-account/get-mint-account.en.ts
- code/token/get-mint-account/get-mint-account.preview.en.ts
- code/token/get-token-account/get-token-account.en.ts
- code/token/get-token-account/get-token-account.preview.en.ts
- code/token/mint-token/mint-token.en.ts
- code/token/mint-token/mint-token.preview.en.ts
- code/token/revoke/main.en.ts
- code/token/revoke/main.preview.en.ts
- code/token/set-authority/main.en.ts
- code/token/set-authority/main.preview.en.ts
- code/token/transfer-token/transfer-token.en.ts
- code/token/transfer-token/transfer-token.preview.en.ts
- code/token/wrapped-sol/add-balance-by-sol.en.ts
- code/token/wrapped-sol/add-balance-by-sol.preview.en.ts
- code/token/wrapped-sol/add-balance-by-token.en.ts
- code/token/wrapped-sol/add-balance-by-token.preview.en.ts
- docs/references/token.md
update all token related code to new version lib
> use new version @solana/spl-token lib

- docs/.vuepress/components/SolanaCodeGroup.vue
- docs/.vuepress/components/SolanaCodeGroupItem.vue
- docs/.vuepress/styles/index.scss
Sorry for Completing this Late. I have Changed the Color of the text and the Toggle is Working when the code expands. But for equal spacing when i try to add like padding or margin to the div I get this kind of effect and didn't wanted to change any other css done before So found it strange.
i
> Update code preview

- code/keypairs-and-wallets/connect-to-wallet/connect-to-wallet-svelte.en.html
- code/keypairs-and-wallets/connect-to-wallet/connect-to-wallet-svelte.preview.en.html
- docs/getting-started/installation.md
- docs/references/keypairs-and-wallets.md
This PR makes reference to the #50 Issue
> Svelte wallet adapter snippet

- docs/references/anchor.md
Resolves [#316](https://github.com/solana-developers/solana-cookbook/issues/316)
> fix: update anchor error codes - Issue #316

- docs/getting-started/installation.md
For me personally the older version was not installing incorrectly on my system and I had to manually enter 1.9.16 in each command, so I updated the windows version to include that.
> Update Windows version

- code/keypairs-and-wallets/check-valid-publickey/check-valid-publickey.preview.py
- code/keypairs-and-wallets/check-valid-publickey/check-valid-publickey.preview.rs
- code/keypairs-and-wallets/check-valid-publickey/check-valid-publickey.preview.ts
- code/keypairs-and-wallets/check-valid-publickey/check-valid-publickey.py
- code/keypairs-and-wallets/check-valid-publickey/check-valid-publickey.rs
- code/keypairs-and-wallets/check-valid-publickey/check-valid-publickey.ts
- docs/references/keypairs-and-wallets.md
> feat: add user public key valid check

- docs/.vuepress/config.ts
- docs/integrations/react-native.md
This is a first go at the React Native tutorial for Solana. 
Please give me feedback on the content or tone of voice, happy to tweak things where needed!
> feat(docs): add React Native tutorial

- docs/core-concepts/programs.md
The original one is not maintained anymore
> fix: update URI of resource

- code/nfts/get-all-nfts/get-all-nfts.en.ts
- code/nfts/get-all-nfts/get-all-nfts.preview.en.ts
- code/nfts/get-metadata/get-metadata.en.ts
- code/nfts/get-metadata/get-metadata.preview.en.ts
- code/nfts/mint-nft/mint-nft.en.ts
- code/nfts/mint-nft/mint-nft.preview.en.ts
> fix: update the nft reference snippets to use the new metaplex sdk

- docs/references/nfts.md
Hi there, just dropping in a small [grammar](https://dictionary.cambridge.org/grammar/british-grammar/different-from-different-to-or-different-than) fix!
> Fix small grammar error in NFT guide

- code/token/get-mint-account/get-mint-account.preview.en.ts
getMint(connection, mintAccountPublicKey);
> Fix mislabeled variable (preview)

- docs/references/basic-transactions.md
Changes based on feedback from Tao.
> Changes based on feedback from Tao.

- code/name-service/resolve-sol-domain/resolve-sol-domain.en.ts
- code/name-service/resolve-sol-domain/resolve-sol-domain.preview.en.ts
confirm and tested, this should fix #419
> fix: owner.owner to owner.registry.owner

- code/accounts/get-balance/main.en.py
- code/accounts/get-balance/main.preview.en.py
- code/anchor/testing-with-anchor/client/testing_with_anchor.py
- code/basic-transactions/sending-sol/sending-sol.en.py
- code/basic-transactions/sending-sol/sending-sol.preview.en.py
- code/keypairs-and-wallets/check-valid-publickey/check-valid-publickey.preview.py
- code/keypairs-and-wallets/check-valid-publickey/check-valid-publickey.py
- code/keypairs-and-wallets/generate-keypair/generate-keypair.en.py
- code/keypairs-and-wallets/keypair-from-secret/from-bs58.en.py
- code/keypairs-and-wallets/keypair-from-secret/from-bs58.preview.en.py
- code/keypairs-and-wallets/keypair-from-secret/keypair-from-secret.en.py
- code/keypairs-and-wallets/keypair-from-secret/keypair-from-secret.preview.en.py
- code/keypairs-and-wallets/mnemonic-to-keypair/from-bip39.preview.py
- code/keypairs-and-wallets/mnemonic-to-keypair/from-bip39.py
- code/keypairs-and-wallets/sign-verify-message/sign-verify-message.en.py
- code/keypairs-and-wallets/sign-verify-message/sign-verify-message.preview.en.py
- code/keypairs-and-wallets/vanity-publickeys/vanity-publickeys.en.py
- code/keypairs-and-wallets/vanity-publickeys/vanity-publickeys.preview.en.py
- code/keypairs-and-wallets/verify-keypair/verify-keypair.en.py
- code/keypairs-and-wallets/verify-keypair/verify-keypair.preview.en.py
- code/local-development/airdropping-sol/airdropping-sol.en.py
- code/local-development/airdropping-sol/airdropping-sol.preview.en.py
- code/local-development/connecting-websocket/connecting-websocket.en.py
- code/local-development/connecting-websocket/connecting-websocket.preview.en.py
- code/serialization/clientdata/python.client.data.py
- code/serialization/instruction/python.client.py
- code/serialization/primitives/python.demo_primitives.py
The Python examples are out of date because of changes to solders and solana-py
> Update python examples

- code/switchboard/on-chain/read.on-chain.en.rs
- code/switchboard/on-chain/read.on-chain.preview.en.rs
@jacobcreech Updated the switchboard read feed example to work with the latest sdk
> fix: update read feed example

- docs/.vuepress/config.ts
- docs/core-concepts/cpi.md
Add overview of CPIs to Core Concepts
https://github.com/solana-developers/solana-cookbook/issues/166
> feat: add cpi core concept page

- code/get-program-accounts/dataSlice/dataSlice.en.rs
> Rust comment adaptation in <dataSlice.en.rs>

- docs/gaming/game-sdks.md
the Seahorse repo has moved and new docs have been built for it
I've updated the links to reflect this
>  Links updated for Seahorse

- code/get-program-accounts/dataSlice/dataSlice.en.rs
- code/get-program-accounts/memcmp/memcmp.en.rs
> chore: update `Memcmp` to use constructor method #558

- code/accounts/close-account/client/close-account.adapter.en.tsx
- code/accounts/close-account/client/close-account.adapter.preview.en.tsx
- docs/references/accounts.md
Add to References -> Accounts -> How to close accounts -> with wallet adaptor
> add: close accounts with wallet adapter

- code/keypairs-and-wallets/mnemonic-to-keypair/from-bip44.preview.py
- code/keypairs-and-wallets/mnemonic-to-keypair/from-bip44.py
- docs/references/keypairs-and-wallets.md
This pull request was created by https://app.gib.work/r/ud7vNGtQ/solana-cookbook in an attempt to solve a bounty. Payment for the bounty is immediately sent to the contributor after merge.
> feat(python): Added python snippet to restore a Keypair from a mnemonic phrase (BIP44)
