- code/keypairs-and-wallets/sign-verify-message/sign-verify-message.preview.en.ts
- code/keypairs-and-wallets/sign-verify-message/sign-verify-message.ts
- docs/recipes/keypairs-and-wallets.md
Added snippet to be able to sign and verify messages using the [TweetNaCl](http://tweetnacl.cr.yp.to/) js library.
Did not add the encrypt/decrypt use-case.
> [Snippet]: Issue #52

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- README.md
Fixes #77 
Build environment defined in development container.
Build instructions to the README.
> feat(build-env): Add VS Code dev container

- code/keypairs-and-wallets/connect-to-wallet/connect-to-wallet-react.en.tsx
- code/keypairs-and-wallets/connect-to-wallet/connect-to-wallet-react.preview.en.tsx
- docs/recipes/keypairs-and-wallets.md
Addresses the `React` portion of #50, namely:
1. Wrapping React App with necessary providers to use the @solana/wallet-adapter-react-* packages
2. Prompting the user to connect to their wallet if they aren't connected
I'm not sure if there were more specific instructions that I missed, so let me know if I need to fix anything!
> feat(wallet): add snippet for connecting to wallet with react

- code/accounts/create-system-account/create-system-account.en.rs
- code/accounts/create-system-account/create-system-account.preview.en.rs
- docs/recipes/accounts.md
re #127
Might be worth evaluating how much/little should be in the preview
> docs(create account): add rust code snippets for creating an account

- docs/ingredients/serialization.md
Closes #162 
This corrects a typo in the `Serialization` Ingredient’s copy — “occurs.”
> fix: correct instance of occurs

- code/keypairs-and-wallets/verify-keypair/verify-keypair.en.py
- code/keypairs-and-wallets/verify-keypair/verify-keypair.preview.en.py
Use `public_key.to_base58()` instead of `PublicKey.to_base58(public_key)` and make the final print similar to the TS example
> Nit: make verify-keypair.en.py more idiomatic

- docs/references/keypairs-and-wallets.md
The only thing I actually added here was the `::: warning` bit, the rest is just VS Code autoformatting some whitespace 🤷‍♂️
> add warning to use CLI for vanity pubkeys

- code/keypairs-and-wallets/connect-to-wallet/connect-to-wallet-react.en.tsx
fixes out of date syntax for `@solana/wallet-adapter-wallets` in https://github.com/solana-developers/solana-cookbook/pull/116
> fix: react wallet adapter code snippet

- code/offline-transactions/partial-sign/main.en.ts
- code/offline-transactions/partial-sign/main.preview.en.ts
- docs/references/offline-transactions.md
- Intended to address discord question: https://discord.com/channels/428295358100013066/517163444747894795/953743912437166150
- Modified from a NextJS example: https://github.com/mcintyre94/solana-partially-signed
- I've used public/private keys from other code examples
- The token address I've used is the one from https://spl-token-faucet.com
The code creates a transaction where:
- Alice sends Bob 0.01 SOL
- Bob sends Alice 1 token
- Bob partially signs the transaction
- The transaction is serialized + returned
New snippet: https://solana-cookbook-git-fork-mcintyre94-token-tx-pa-b4aeb7-cookbook.vercel.app/references/offline-transactions.html#partial-sign-transaction
> feat: Token transaction w/ partial sign snippet (#293)

- code/basic-transactions/sending-sol/sending-sol.adapter.en.tsx
- code/basic-transactions/sending-sol/sending-sol.adapter.preview.en.tsx
- code/basic-transactions/sending-sol/sending-sol.en.py
- code/basic-transactions/sending-sol/sending-sol.en.rs
- code/basic-transactions/sending-sol/sending-sol.en.sh
- code/basic-transactions/sending-sol/sending-sol.en.ts
- code/basic-transactions/sending-sol/sending-sol.preview.en.py
Since feature _BkFDxiJQWZXGTZaJQxH7wVEHkAmwCgSEVkrvswFfRJPD_, new accounts are required to be rent-exempt. 
```bash
solana rent 0
```
```
Rent-exempt minimum: 0.00089088 SOL
```
**Error:**
- https://github.com/solana-labs/solana/blob/f81c5df1f02b0e41f3e5dd3d236a34818cc40a5a/sdk/src/transaction/error.rs
**Related issues:**
- https://github.com/solana-labs/dapp-scaffold/issues/173
- https://github.com/solana-labs/dapp-scaffold/issues/178
@jacobcreech what do you think about adding this extra quote:
_"If you are sending SOL to an uninitialized account, for example, a new address without an account. Make sure to send an amount above the rent-exempt minimum. The minimum amount to be rent exempt can be found using the CLI with `solana rent 0`"_
> Fixes Error: "Transaction leaves an account with a lower balance than rent-exempt minimum"

- code/token/get-mint-account/get-mint-account.en.ts
`getMint(connection, mint)` does not make logical sense - if you have a mint, you don't need to get a mint.
> Fix mislabeled variable

- docs/references/token.md
Heya! I'm contributing here because my original impression from reading this doc was a little misleading. When I read 
"Every token mint has a different token account associated with it."
I thought this meant that FooToken's mint account would mint to FooToken's token account, and then be transferred to some user's FooToken token account.
From what I've been told, that's incorrect - [talking with others in Solana Stack Exchange](https://solana.stackexchange.com/questions/849/are-new-spl-tokens-typically-transferred-from-a-mints-token-account-to-a-users), it seems that a token is minted directly to a user's token account. FooToken mint account, mints token to Joe Smith's FooToken Token Account.
Is that correct? If so I've made some changes to clarify this, which should help clarify things …
> Clarify that tokens are minted into user's token accounts

- docs/integrations/react-native.md
Folks are starting to [rightfully complain](https://solana.stackexchange.com/questions/2275/error-while-generating-a-build-in-react-native-using-solana-web3-js) that the cookbook directions for React Native no longer work with modern versions of `@solana/web3.js`. This PR updates that recipe.
Essentially, the new directions instruct people to use a version of React Native >=v0.70. An explanation of why can be found here: https://twitter.com/steveluscher/status/1565232091260157952
> Update the React Native integration docs for these modern times

- docs/integrations/react-native.md
Removed the `rc` version and removed hacks that are no longer needed.
> Update the cookbook for the release of React Native 0.70.0

- code/basic-transactions/compute-budget/computeBudget.en.rs
- code/basic-transactions/compute-budget/computeBudget.en.tsx
- code/basic-transactions/compute-budget/computeBudget.preview.en.rs
- code/basic-transactions/compute-budget/computeBudget.preview.en.tsx
- code/basic-transactions/compute-budget/log_output.txt
- docs/references/basic-transactions.md
I updated this section to show how to use the new `ComputeBudgetProgram.setComputeUnitLimit` & `ComputeBudgetProgram.setComputeUnitPrice` instructions. The previous version showed the deprecated method that will soon be removed.
> Revise section to show how to use the new ComputeBudgetProgram

- code/local-development/airdropping-sol/airdropping-sol.en.ts
confirmTransaction in the airdropping-sol TS code block is deprecated. Updated it to the latest confirmTransaction method usage.
> fix: update confirmTransaction method usage in airdropping-sol

- code/name-service/resolve-sub-domain/resolve-sub-domain.preview.en.ts
- docs/kr/references/offline-transactions.md
- docs/tr/references/name-service.md
Line 5, in `code/name-service/resolve-sub-domain/resolve-sub-domain.preview.en.ts`
`mainDomain` is not exist, and is not matched with `hashedParentDomain`.
=> `mainDomain` changed to `parentDomain`
Line 72, in `docs/kr/references/offline-transactions.md`.
There's a defector in Korean references,
=> `Trnascation` changed to `Transaction`
> fix: Correction of defectors in korean references and code examples

- code/nfts/get-all-nfts/get-all-nfts.en.ts
- code/nfts/get-all-nfts/get-all-nfts.preview.en.ts
- code/nfts/get-metadata/get-metadata.en.ts
- code/nfts/get-metadata/get-metadata.preview.en.ts
Updates: 
- [`findByMint`](https://github.com/metaplex-foundation/js#findByMint)
- [`findAllByOwner`](https://github.com/metaplex-foundation/js#findAllByOwner)
Note: Metadata has moved to `json` property of returned NFT: https://github.com/metaplex-foundation/js/blob/main/packages/js/src/plugins/nftModule/models/Metadata.ts#L30
> docs(nfts): update metaplex api examples

- docs/getting-started/installation.md
I fixed the issue with persisting the Solana-cli  command in the terminal on Ubuntu 20.04 and 22.04
> updated the installation docs for solana-cli binaries

- code/basic-transactions/sending-spl-token/sending-spl-token.en.ts
I got following error when I run example codes.
```
const key = signer.publicKey.toString();
^
TypeError: Cannot read properties of undefined (reading 'toString')
at Transaction.apply [as sign]
```
@solana/spl-token changed some functions/methods.
Details: https://stackoverflow.com/a/71496672
I update some codes for latest versions(@solana/spl-token v0.3.8 - 6/1/2023).
- [  ] New feature (non-breaking change which adds functionality)
- [  ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [  ] This change requires a documentation update
> fix: "Cannot read properties of undefined" error
